### ISSUE TITLE
Would be nice to include build directives for macOS

### ISSUE THREAD

**Issue by Jessie-Clarke** [droe/sqlite-hexhammdist#1]
Hi,

Although it works very well, your project is not compilable on macOS. Here are the modified "GNUmakeFile" for macOS 32/64 bits ("so" becomes "dylib" and the different architectures are specified in "$(CC)" as "-arch i386 -arch x86_64")

-----
all: sqlite-hexhammdist.dylib

sqlite-hexhammdist.dylib: sqlite-hexhammdist.c GNUmakefile
	$(CC) -shared -arch i386 -arch x86_64 -fPIC -o $@ $< -lsqlite3

clean:
	rm -f sqlite-hexhammdist.dylib
-----

**Comment by droe** [comment]
As a matter of fact, I develop and use this mainly on macOS, so this is perfectly buildable and usable there. It does not create a multi-architecture library though, fair point, it should do that.

**Comment by droe** [comment]
Addressed by a67fc97, thank you for your request.
